import type { Offer } from "./types";

export const baseOffers: Offer[] = [
  {
    id: "cat-litter-rakuten",
    label: "実質最安",
    labelType: "lowest",
    priceMode: "demo",
    title: "いつもの猫砂 5L x 4袋",
    price: 2380,
    unitPrice: "595円/袋",
    category: "ペット用品",
    retailer: "楽天24",
    shipping: "送料無料",
    points: "162pt還元込み",
    affiliateRate: 0.035,
    detail: "送料・ポイント込みで楽天が最安という想定のデモ価格です。実運用ではEC APIや商品フィードで再計算します。",
    reason: "登録済みの猫砂が残り数日前後のため表示しています。",
    linkText: "比較根拠を見る",
    comparedAt: "デモデータ: 2026-06-12",
    comparisonBasis: ["同容量 5L x 4袋", "送料込み", "ポイント還元を控除", "スポンサー枠より通常最安を優先"],
    competitors: [
      { retailer: "楽天24", price: 2380, shipping: "送料無料", points: "162pt", note: "実質最安として表示" },
      { retailer: "Amazon", price: 2480, shipping: "Prime配送", points: "なし", note: "現金価格は近いがポイント差で下位" },
      { retailer: "Yahoo!", price: 2520, shipping: "送料無料ライン対象", points: "180pt", note: "還元込みでも少し高い想定" },
    ],
  },
  {
    id: "cat-litter-sponsored",
    label: "キャンペーン / 広告",
    labelType: "sponsored",
    priceMode: "demo",
    title: "同容量・消臭タイプ猫砂",
    price: 2260,
    unitPrice: "565円/袋",
    category: "ペット用品",
    retailer: "提携ペットEC",
    shipping: "送料無料",
    points: "初回クーポン適用",
    affiliateRate: 0.08,
    detail: "スポンサー商品ですが、同容量で120円安い場合だけ比較候補として出す想定です。自動購入では勝手に切り替えません。",
    reason: "広告枠ですが、同容量・同カテゴリで価格メリットがあるため比較候補です。",
    linkText: "通常品と比較",
    comparedAt: "デモデータ: 2026-06-12",
    comparisonBasis: ["同容量", "初回クーポン込み", "広告ラベルを明示", "ブランド変更は承認必須"],
    competitors: [
      { retailer: "提携ペットEC", price: 2260, shipping: "送料無料", points: "初回クーポン", note: "スポンサー候補" },
      { retailer: "楽天24", price: 2380, shipping: "送料無料", points: "162pt", note: "通常の実質最安候補" },
      { retailer: "Amazon", price: 2480, shipping: "Prime配送", points: "なし", note: "配送は速いが価格は高め" },
    ],
  },
  {
    id: "detergent-amazon",
    label: "実質最安",
    labelType: "lowest",
    priceMode: "demo",
    title: "洗濯洗剤 詰め替え 720g",
    price: 698,
    unitPrice: "96.9円/100g",
    category: "洗濯・掃除",
    retailer: "Amazon",
    shipping: "Prime配送",
    points: "現金価格最安",
    affiliateRate: 0.025,
    detail: "Amazonが現金価格最安という想定です。実運用ではポイント、送料、クーポンを同じ式で比較します。",
    reason: "洗濯洗剤の残量と世帯人数から10日以内の補充候補です。",
    linkText: "価格推移を見る",
    comparedAt: "デモデータ: 2026-06-12",
    comparisonBasis: ["720g換算", "送料込み", "ポイント込み価格も比較", "通常価格を最優先"],
    competitors: [
      { retailer: "Amazon", price: 698, shipping: "Prime配送", points: "なし", note: "現金価格最安" },
      { retailer: "Yahoo!", price: 748, shipping: "送料無料ライン対象", points: "60pt", note: "還元込みで同水準" },
      { retailer: "楽天24", price: 790, shipping: "まとめ買い送料無料", points: "45pt", note: "単品では高め" },
    ],
  },
  {
    id: "baby-wipes-coupon",
    label: "キャンペーン / 広告",
    labelType: "sponsored",
    priceMode: "demo",
    title: "おしりふき まとめ買いクーポン",
    price: 1480,
    unitPrice: "185円/個",
    category: "ベビー用品",
    retailer: "ベビー用品EC",
    shipping: "3,000円以上送料無料",
    points: "15%OFFクーポン",
    affiliateRate: 0.07,
    detail: "ベビー用品登録世帯だけに表示する送客枠です。広告でも表示条件と割引理由を見せます。",
    reason: "子どもがいる世帯設定か、ベビー用品在庫がある場合だけ表示します。",
    linkText: "クーポンを見る",
    comparedAt: "デモデータ: 2026-06-12",
    comparisonBasis: ["同枚数に換算", "クーポン適用後", "送料条件を表示", "対象世帯のみ表示"],
    competitors: [
      { retailer: "ベビー用品EC", price: 1480, shipping: "3,000円以上送料無料", points: "15%OFF", note: "スポンサー候補" },
      { retailer: "Amazon", price: 1580, shipping: "Prime配送", points: "なし", note: "配送は速い" },
      { retailer: "楽天24", price: 1640, shipping: "送料無料ライン対象", points: "80pt", note: "買い回りで逆転余地" },
    ],
  },
  {
    id: "water-yahoo",
    label: "実質最安",
    labelType: "lowest",
    priceMode: "demo",
    title: "ミネラルウォーター 2L x 9本",
    price: 1080,
    unitPrice: "60円/L",
    category: "食品・飲料",
    retailer: "Yahoo!ショッピング",
    shipping: "送料無料ライン対象",
    points: "PayPay還元込み",
    affiliateRate: 0.02,
    detail: "重い定番品は配送価値が高く、まとめ買いで送料無料ラインに乗せる想定です。",
    reason: "食品・飲料の残量が少ない場合のまとめ買い候補です。",
    linkText: "まとめ買いを見る",
    comparedAt: "デモデータ: 2026-06-12",
    comparisonBasis: ["2L x 9本", "送料込み", "PayPay還元込み", "重量物の配送価値を表示"],
    competitors: [
      { retailer: "Yahoo!ショッピング", price: 1080, shipping: "送料無料ライン対象", points: "PayPay還元", note: "実質最安候補" },
      { retailer: "Amazon", price: 1180, shipping: "Prime配送", points: "なし", note: "配送速度は強い" },
      { retailer: "楽天24", price: 1260, shipping: "送料無料ライン対象", points: "100pt", note: "まとめ買い向き" },
    ],
  },
];
