import type { Offer, OfferCondition } from "./types";

const firstOrderCoupon: OfferCondition = {
  label: "条件あり",
  detail: "初回購入クーポンの適用が必要です。既に利用済みのアカウントでは通常価格になります。",
};

const pointBack: OfferCondition = {
  label: "条件あり",
  detail: "ポイント還元込みの実質価格です。ポイント付与時期と利用先は販売サイトの条件を確認してください。",
};

const freeShippingLine: OfferCondition = {
  label: "条件あり",
  detail: "一定金額以上の購入で送料無料になります。単品購入では送料が加算される場合があります。",
};

export const baseOffers: Offer[] = [
  {
    id: "cat-litter-petplus-coupon",
    priceMode: "demo",
    title: "固まる猫砂 5L x 4袋",
    listPrice: 2480,
    effectivePrice: 2260,
    unitPrice: "565円 / 袋",
    category: "ペット用品",
    retailer: "PetPlus公式",
    url: "https://www.google.com/search?q=PetPlus+%E7%8C%AB%E7%A0%82+5L+4%E8%A2%8B",
    shipping: "送料無料",
    points: "初回10%OFFクーポン込み",
    affiliateRate: 0.08,
    detail: "初回クーポンを使うと価格順1位になります。通常価格では楽天24より高くなるため、条件確認が必要です。",
    reason: "同容量の商品で、クーポン適用後の実質価格が最も低い候補です。",
    linkText: "条件と商品ページを見る",
    comparedAt: "デモデータ: 2026-06-12",
    conditions: [firstOrderCoupon],
    comparisonBasis: ["5L x 4袋", "送料込み", "クーポン・ポイント込みの実質価格", "同カテゴリ・同容量で比較"],
    competitors: [
      {
        retailer: "PetPlus公式",
        url: "https://www.google.com/search?q=PetPlus+%E7%8C%AB%E7%A0%82+5L+4%E8%A2%8B",
        listPrice: 2480,
        effectivePrice: 2260,
        shipping: "送料無料",
        points: "初回10%OFF",
        conditions: [firstOrderCoupon],
        note: "初回クーポン適用時の実質価格",
      },
      {
        retailer: "楽天24",
        url: "https://search.rakuten.co.jp/search/mall/%E7%8C%AB%E7%A0%82+5L+4%E8%A2%8B/",
        listPrice: 2380,
        effectivePrice: 2380,
        shipping: "送料無料",
        points: "通常ポイント",
        conditions: [],
        note: "条件なしで安い候補",
      },
      {
        retailer: "Amazon",
        url: "https://www.amazon.co.jp/s?k=%E7%8C%AB%E7%A0%82+5L+4%E8%A2%8B",
        listPrice: 2480,
        effectivePrice: 2480,
        shipping: "Prime配送",
        points: "なし",
        conditions: [],
        note: "配送は速いが価格はやや高め",
      },
    ],
  },
  {
    id: "cat-litter-rakuten",
    priceMode: "demo",
    title: "固まる猫砂 5L x 4袋",
    listPrice: 2380,
    effectivePrice: 2380,
    unitPrice: "595円 / 袋",
    category: "ペット用品",
    retailer: "楽天24",
    url: "https://search.rakuten.co.jp/search/mall/%E7%8C%AB%E7%A0%82+5L+4%E8%A2%8B/",
    shipping: "送料無料",
    points: "通常ポイント",
    affiliateRate: 0.035,
    detail: "クーポンなしで買える安定候補です。条件付き価格が使えない場合の基準価格として表示します。",
    reason: "猫砂の残日数が少ないため、条件なしで購入できる価格候補として表示しています。",
    linkText: "商品ページを見る",
    comparedAt: "デモデータ: 2026-06-12",
    conditions: [],
    comparisonBasis: ["5L x 4袋", "送料込み", "条件なし価格", "同カテゴリ・同容量で比較"],
    competitors: [
      {
        retailer: "楽天24",
        url: "https://search.rakuten.co.jp/search/mall/%E7%8C%AB%E7%A0%82+5L+4%E8%A2%8B/",
        listPrice: 2380,
        effectivePrice: 2380,
        shipping: "送料無料",
        points: "通常ポイント",
        conditions: [],
        note: "条件なしで安い候補",
      },
      {
        retailer: "PetPlus公式",
        url: "https://www.google.com/search?q=PetPlus+%E7%8C%AB%E7%A0%82+5L+4%E8%A2%8B",
        listPrice: 2480,
        effectivePrice: 2260,
        shipping: "送料無料",
        points: "初回10%OFF",
        conditions: [firstOrderCoupon],
        note: "条件を満たすと安い",
      },
      {
        retailer: "Yahoo!ショッピング",
        url: "https://shopping.yahoo.co.jp/search?p=%E7%8C%AB%E7%A0%82+5L+4%E8%A2%8B",
        listPrice: 2520,
        effectivePrice: 2340,
        shipping: "送料無料ライン対象",
        points: "PayPay還元込み",
        conditions: [pointBack, freeShippingLine],
        note: "還元込みなら近い価格",
      },
    ],
  },
  {
    id: "detergent-amazon",
    priceMode: "demo",
    title: "洗濯洗剤 詰め替え 720g",
    listPrice: 698,
    effectivePrice: 698,
    unitPrice: "96.9円 / 100g",
    category: "洗濯・掃除",
    retailer: "Amazon",
    url: "https://www.amazon.co.jp/s?k=%E6%B4%97%E6%BF%AF%E6%B4%97%E5%89%A4+%E8%A9%B0%E3%82%81%E6%9B%BF%E3%81%88+720g",
    shipping: "Prime配送",
    points: "なし",
    affiliateRate: 0.025,
    detail: "単品でも買いやすい条件なしの価格です。",
    reason: "洗濯洗剤の残日数が10日以内に近いため、補充候補として表示しています。",
    linkText: "商品ページを見る",
    comparedAt: "デモデータ: 2026-06-12",
    conditions: [],
    comparisonBasis: ["720g詰め替え", "送料込み", "条件なし価格を優先", "同容量で比較"],
    competitors: [
      {
        retailer: "Amazon",
        url: "https://www.amazon.co.jp/s?k=%E6%B4%97%E6%BF%AF%E6%B4%97%E5%89%A4+%E8%A9%B0%E3%82%81%E6%9B%BF%E3%81%88+720g",
        listPrice: 698,
        effectivePrice: 698,
        shipping: "Prime配送",
        points: "なし",
        conditions: [],
        note: "条件なしの価格順1位",
      },
      {
        retailer: "Yahoo!ショッピング",
        url: "https://shopping.yahoo.co.jp/search?p=%E6%B4%97%E6%BF%AF%E6%B4%97%E5%89%A4+%E8%A9%B0%E3%82%81%E6%9B%BF%E3%81%88+720g",
        listPrice: 748,
        effectivePrice: 688,
        shipping: "送料無料ライン対象",
        points: "PayPay還元込み",
        conditions: [pointBack, freeShippingLine],
        note: "還元込みなら安い",
      },
      {
        retailer: "楽天24",
        url: "https://search.rakuten.co.jp/search/mall/%E6%B4%97%E6%BF%AF%E6%B4%97%E5%89%A4+%E8%A9%B0%E3%82%81%E6%9B%BF%E3%81%88+720g/",
        listPrice: 790,
        effectivePrice: 745,
        shipping: "まとめ買いで送料無料",
        points: "ポイント込み",
        conditions: [pointBack, freeShippingLine],
        note: "まとめ買い向き",
      },
    ],
  },
  {
    id: "baby-wipes-coupon",
    priceMode: "demo",
    title: "おしりふき 8個パック",
    listPrice: 1640,
    effectivePrice: 1480,
    unitPrice: "185円 / 個",
    category: "ベビー用品",
    retailer: "ベビー用品公式",
    url: "https://www.google.com/search?q=%E3%81%8A%E3%81%97%E3%82%8A%E3%81%B5%E3%81%8D+8%E5%80%8B%E3%83%91%E3%83%83%E3%82%AF+%E5%85%AC%E5%BC%8F",
    shipping: "3,000円以上で送料無料",
    points: "15%OFFクーポン込み",
    affiliateRate: 0.07,
    detail: "クーポンと送料無料ラインを満たすと安くなります。単品購入では送料条件を確認してください。",
    reason: "子どもがいる世帯、またはベビー用品の在庫がある場合に表示します。",
    linkText: "条件と商品ページを見る",
    comparedAt: "デモデータ: 2026-06-12",
    conditions: [firstOrderCoupon, freeShippingLine],
    comparisonBasis: ["同梱数で比較", "クーポン適用後", "送料条件を表示", "対象世帯のみ表示"],
    competitors: [
      {
        retailer: "ベビー用品公式",
        url: "https://www.google.com/search?q=%E3%81%8A%E3%81%97%E3%82%8A%E3%81%B5%E3%81%8D+8%E5%80%8B%E3%83%91%E3%83%83%E3%82%AF+%E5%85%AC%E5%BC%8F",
        listPrice: 1640,
        effectivePrice: 1480,
        shipping: "3,000円以上で送料無料",
        points: "15%OFF",
        conditions: [firstOrderCoupon, freeShippingLine],
        note: "条件込みの価格順1位",
      },
      {
        retailer: "Amazon",
        url: "https://www.amazon.co.jp/s?k=%E3%81%8A%E3%81%97%E3%82%8A%E3%81%B5%E3%81%8D+8%E5%80%8B%E3%83%91%E3%83%83%E3%82%AF",
        listPrice: 1580,
        effectivePrice: 1580,
        shipping: "Prime配送",
        points: "なし",
        conditions: [],
        note: "条件なしで買いやすい",
      },
      {
        retailer: "楽天24",
        url: "https://search.rakuten.co.jp/search/mall/%E3%81%8A%E3%81%97%E3%82%8A%E3%81%B5%E3%81%8D+8%E5%80%8B%E3%83%91%E3%83%83%E3%82%AF/",
        listPrice: 1640,
        effectivePrice: 1560,
        shipping: "送料無料ライン対象",
        points: "ポイント込み",
        conditions: [pointBack, freeShippingLine],
        note: "まとめ買いで候補",
      },
    ],
  },
  {
    id: "water-yahoo",
    priceMode: "demo",
    title: "ミネラルウォーター 2L x 9本",
    listPrice: 1180,
    effectivePrice: 1080,
    unitPrice: "60円 / L",
    category: "食品・飲料",
    retailer: "Yahoo!ショッピング",
    url: "https://shopping.yahoo.co.jp/search?p=%E3%83%9F%E3%83%8D%E3%83%A9%E3%83%AB%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%BF%E3%83%BC+2L+9%E6%9C%AC",
    shipping: "送料無料ライン対象",
    points: "PayPay還元込み",
    affiliateRate: 0.02,
    detail: "ポイント還元込みの実質価格です。重量物なので配送条件も合わせて表示します。",
    reason: "水の在庫が少ない場合のまとめ買い候補です。",
    linkText: "条件と商品ページを見る",
    comparedAt: "デモデータ: 2026-06-12",
    conditions: [pointBack, freeShippingLine],
    comparisonBasis: ["2L x 9本", "送料込み条件", "PayPay還元込み", "重量物の配送価値を表示"],
    competitors: [
      {
        retailer: "Yahoo!ショッピング",
        url: "https://shopping.yahoo.co.jp/search?p=%E3%83%9F%E3%83%8D%E3%83%A9%E3%83%AB%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%BF%E3%83%BC+2L+9%E6%9C%AC",
        listPrice: 1180,
        effectivePrice: 1080,
        shipping: "送料無料ライン対象",
        points: "PayPay還元込み",
        conditions: [pointBack, freeShippingLine],
        note: "条件込みの価格順1位",
      },
      {
        retailer: "Amazon",
        url: "https://www.amazon.co.jp/s?k=%E3%83%9F%E3%83%8D%E3%83%A9%E3%83%AB%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%BF%E3%83%BC+2L+9%E6%9C%AC",
        listPrice: 1180,
        effectivePrice: 1180,
        shipping: "Prime配送",
        points: "なし",
        conditions: [],
        note: "配送速度が強い",
      },
      {
        retailer: "楽天24",
        url: "https://search.rakuten.co.jp/search/mall/%E3%83%9F%E3%83%8D%E3%83%A9%E3%83%AB%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%BF%E3%83%BC+2L+9%E6%9C%AC/",
        listPrice: 1260,
        effectivePrice: 1160,
        shipping: "送料無料ライン対象",
        points: "ポイント込み",
        conditions: [pointBack, freeShippingLine],
        note: "まとめ買い向き",
      },
    ],
  },
];
